
services:
  yolo5:
    image: ${YOLO5_IMG_NAME}
    container_name: yolo5
    ports:
      - "8081:8081"
    environment:
      AWS_REGION: ${AWS_REGION}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      SQS_URL: ${SQS_URL}
      SQS_QUEUE_NAME: ${SQS_URL}
    volumes:
      - ./logs:/usr/src/app/logs
    restart: always
