services:
  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: polybot
    ports:
      - "8443:8443"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_APP_URL: ${TELEGRAM_APP_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      SQS_URL: ${SQS_URL}
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - polybot-network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    networks:
      - polybot-network

networks:
  polybot-network:
    driver: bridge
