name: Infrastructure Terraform Main

on:
  workflow_dispatch:
    inputs:
      us-east-1:
        description: 'N.Virginia (us-east-1)'
        required: false
        type: boolean
      eu-central-1:
        description: 'Frankfurt (eu-central-1)'
        required: false
        type: boolean

jobs:
  us-east-1:
    if: ${{ github.event.inputs.us-east-1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: us-east-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.US_EAST_1_TELEGRAM_TOKEN }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

  eu-central-1:
    if: ${{ github.event.inputs.eu-central-1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: eu-central-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.EU_CENTRAL_1_TELEGRAM_TOKEN }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
