name: Infrastructure Terraform Specific Region

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
    secrets:
      TELEGRAM_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_PRIVATE_KEY:  # Add this line to declare the AWS_PRIVATE_KEY secret
        required: true

jobs:
  Terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.7

      - name: Set up AWS credentials
        run: |
          echo "AWS credentials are set through the job's env context."

      - name: Terraform init
        working-directory: ./tf
        run: terraform init

      - name: Terraform workspace select or create
        working-directory: ./tf
        run: |
          terraform workspace select ${{ inputs.region-code }} || terraform workspace new ${{ inputs.region-code }}

      - name: Terraform validate
        working-directory: ./tf
        run: terraform validate

      - name: Terraform plan
        working-directory: ./tf
        run: |
          echo "Running Terraform plan for region ${{ inputs.region-code }}"
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          terraform plan -var-file=region.${{ inputs.region-code }}.tfvars

      - name: Terraform apply
        working-directory: ./tf
        run: |
          echo "Applying Terraform changes"
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          export TF_VAR_aws_private_key="${{ secrets.AWS_PRIVATE_KEY }}"
          terraform apply -auto-approve -var "aws_private_key=${{ secrets.AWS_PRIVATE_KEY }}" -var-file=region.${{ inputs.region-code }}.tfvars
