name: Terraform Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Select the AWS region'
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - us-east-1
          - eu-west-1

jobs:
  destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us-east-1, eu-west-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        run: |
          curl -LO "https://github.com/hashicorp/terraform/releases/latest/download/terraform_$(uname | tr '[:lower:]' '[:upper:]')_amd64.zip"
          unzip terraform_*.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Terraform Init
        run: terraform init -backend-config="region=${{ matrix.region }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var "aws_private_key=${{ secrets.AWS_PRIVATE_KEY }}" -var-file="region.${{ matrix.region }}.tfvars"
